// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcpsoyorsaevkabvanrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcHNveW9yc2FldmthYnZhbnJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDQwNTAsImV4cCI6MjA2NzEyMDA1MH0.cTx3kPleXF4QxJNRWsOgn73wiMY51XO_1K9Crio_-bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});